---
title: "Example: predator-prey model"
output: rmarkdown::html_vignette
knit: (function(inputFile, encoding, output_dir) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_dir=paste0(dirname(normalizePath(getwd())), "/inst/doc"))})
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r}
# install and load the package
#install.packages("devtools")
#devtools::install_github("r-and-gama/rama")
library(rama)

# if necessary to configure GAMA path
# defpath("/Applications/Gama.app")

# load the experiment
exp <- load_experiment("prey_predator",
                       system.file("models", "NicolasPred.gaml",
                                   package = "rama"))

# to explore the parameters and the observed variables
parameters(exp)
obs_rates(exp)

# to set the experiment
exp$p_Initial_number_of_preys_ <- 990L
exp$p_Initial_number_of_predators_ <- 100L
#exp$p_Predator_probability_reproduce_ <- 0.1
exp$tmax <- 100L

# to run the experiment (do not run)
#out <- run_experiment(exp, hpc = 2)

# to visualize the output
with(out[[1]], plot(Step, `Number of preys`, type = "l", lwd = 2, col = "red"))

#makemovie(out[[1]])
```

